### ISSUE TITLE
'query' does not exist in type 'QueryFn'

### ISSUE THREAD

**Issue by Hillel-Nagid** [wesdoyle/base-chat#1]
`'query' does not exist in type 'QueryFn'`
```  getMessages(): FirebaseListObservable<ChatMessage[]> {
    return this.db.list('messages', {
      query: {
        limitToLast: 25,
        orderByKey: true
      }
    });
  }```
how can I fix that

**Comment by rijomonr** [comment]
I'm getting the same issue Argument of type '{ query: { limitTolast: number; orderByKey: boolean; }; }' is not assignable to parameter of type 'QueryFn'.
  Object literal may only specify known properties, and 'query' does not exist in type 'QueryFn'.

**Comment by 3669** [comment]
hii. i have this problem also. Maybe you found what need to do yet?

**Comment by 3669** [comment]
firstly it's  need to be together
//import { AngularFireDatabase, FirebaseListObservable } from 'angularfire2/database-deprecated';

secondly it's my funcshion

getMessages(): FirebaseListObservable<ChatMessage[]> {
    // query to create our message feed binding
    return this.db.list('message', {
      query: {
        limitToLast: 20
      }
    });
  }

and it's work  now.

**Comment by Hillel-Nagid** [comment]
Thanks 3669

**Comment by jdevsan** [comment]
ERROR in src/app/services/chat.service.ts(55,39): error TS2345: Argument of type '{ query: { limitToLast: number; }; }' is not assignable to parameter of type 'FirebaseListFactoryOpts'.
  Types of property 'query' are incompatible.
    Type '{ limitToLast: number; }' is not assignable to type 'Query'.
      Property 'endAt' is missing in type '{ limitToLast: number; }'.
whats happening??

-----------------------------------
chat.services.ts

getMessages(): FirebaseListObservable<ChatMessage[]> {
      // query to create our message feed binding
      return this.db.list('messages', {
        query: {
          limitToLast: 20,
        
        }
      });
    }

**Comment by pranjul29** [comment]
ERROR in src/app/services/chat.service.ts(48,7): error TS2345: Argument of type '{ query: { limitToLast: number; orderByKey: boolean; }; }' is not assignable to parameter of type 'QueryFn'.
  Object literal may only specify known properties, and 'query' does not exist in type 'QueryFn'.
../../node_modules/rxjs-compat/Observable.d.ts(1,28): error TS2307: Cannot find module 'rxjs'.
../../node_modules/rxjs-compat/Observable.d.ts(2,70): error TS2307: Cannot find module 'rxjs'.

**Comment by ramzan-ali-suzan** [comment]
For AngularFire version 5 and up use,

`db.list('/items', ref => ref.orderByChild('size').equalTo('large'));`

for details please refer [here](https://github.com/angular/angularfire/blob/master/docs/rtdb/querying-lists.md)
